.TH "xprodmode" "1" "Nov 26 2023" "\ \&" "\ \&"

.SH "NAME"
xprodmode \- prevents your computer from falling asleep

.SH "SYNOPSIS"
xprodmode [options]

.SH "DESCRIPTION"
Command line program that uses the left shitf key or move the cursor in random places of the screen.

.SH "OPTIONS"
.sp
.PP
\fB\-h, --help\fR
.RS 4
Show help message and quit\&.
.RE
.PP
\fB\-k, --key\fR
.RS 4
Press the left shift key every 59 seconds\&.
.RE
.PP
\fB\-b, --buggy\fR
.RS 4
Move the cursor in random places of the screen\&.
.RE
.PP
\fB\-v, --version\fR
.RS 4
Show version number and quit\&.
.RE
.PP

.SH "SEE ALSO"

.SH "AUTHORS"
Developed by Alejandro Díaz.
